version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo python3 -m venv venv
            . venv/bin/activate
            python -m pip install requests
            python -m pip install jsonpath
            python -m unittest discover
