version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo python3 -m venv venv
            . venv/bin/activate
            sudo pip install requests
            sudo pip install jsonpath
            python -m unittest discover

