version: 2
jobs:
  build:
    working_directory: ~/python-ci

    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1

    steps:
      - checkout
	  - run:
          name: Install python test dependencies
          command: |
            pip install requests
            pip install jsonpath
	  - run:
          name: Run test application
          command: python -m unittest discover
